# Generated by Django 5.1.7 on 2025-03-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicant',
            name='date_birth',
            field=models.DateField(),
        ),
    ]
