# Generated by Django 5.1.7 on 2025-04-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loanapplicant_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
