# Generated by Django 5.1.7 on 2025-03-29 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0002_alter_user_date_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contraseña',
            new_name='password',
        ),
    ]
