# Generated by Django 5.1.7 on 2025-03-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0003_rename_contraseña_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No-binario'), ('OTHER', 'Otro'), ('PREFER_NOT_TO_SAY', 'Prefiero no decirlo')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('client', 'Cliente')], max_length=255),
        ),
    ]
